spring:
  application:
    name: mytest
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: utf-8

server:
  port: 9090

myConfig:
  myObject:
    myName: zhangshan
    myAge: 20