spring:
  application:
    name: mytest
  #mandatory-file-encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: utf-8

server:
  port: 9090

myConfig:
  myObject:
    myName: zhangshan
    myAge: 20

logging:
  level:
    root: info
    org.springframework: info
    java.sql.Connection: debug
    java.sql.Statement: debug
    org.apache: info
    org.mongodb.driver: info
    com.bob: debug
  path: logs/mylog
